
font_size 14
font_family      Hurmit Nerd Font

window_padding_width 2
background_opacity 0.9

wheel_scroll_multiplier 1

include gruvbox_dark.conf

[Cursor customization]
	cursor #fbf1c7
	cursor_text_color #1d2021
#---------------------------------------
 cursor_shape underline
 cursor_underline_thickness 1.0
#---------------------------------------
cursor_shape beam
cursor_beam_thickness 2.0
#---------------------------------------
#	cursor_shape block
#---------------------------------------
	cursor_blink_interval -1
	cursor_stop_blinking_after 15.0
	cursor_trail 1
	cursor_trail_decay 0.1 0.2
	cursor_trail_start_threshold 0
